Repository MightyITExplorer/Website, pull requests merged in 2023-03, with the labels that each got.

#75 Contact us form Validations added
  index.html
Labels: JWOC, Easy

#83 Improved Nav Responsiveness
  assets/css/index.css
  assets/css/splash.css
  assets/css/theme.css
  assets/js/focusChange.js
  assets/js/theme.js
  index.html
  news.html
  opportunity.html
  studymaterial.html
  testimonial.html
Labels: JWOC, medium

#89 Footer links in different tabs
  index.html
Labels: good first issue, JWOC, Easy

#84 Issue #16 Added More Cards
  opportunity.html
  studymaterial.html
Labels: JWOC, Easy

#80 Added Animated Landing page
  assets/css/splash.css
  assets/js/landing.js
  assets/js/splash.js
  index.html
  landing.html
Labels: JWOC, hard

#101 Fixed Offcanvas Navbar bug
  assets/css/index.css
Labels: JWOC, Easy

#103 Issue #102
  index.html
Labels: JWOC, Easy

#107 Updated index.html
  index.html
Labels: JWOC, Easy

#109 Updated Readme.md with Screen recording of the live project and with some footer
  README.md
Labels: JWOC, Easy

#108 Updated images to work in dark mode in Why collaborate section
  Website/assets/img/energy.png
  Website/assets/img/no-fee.png
  Website/assets/img/transformation.png
  assets/img/energy.png
  assets/img/no-fee.png
  assets/img/transformation.png
Labels: JWOC, Easy

#105 [UPDATE] Opportunity Card Update with responsive
  assets/css/theme.css
Labels: JWOC, Easy

#112 fixed testimonial
  assets/css/testimonial.css
  index.html
  news.html
  opportunity.html
  studymaterial.html
  testimonial.html
Labels: JWOC, Easy

#117 changed the opportunities page
  assets/css/bootstrap.min.css
  assets/css/news.css
  assets/img/Indian_Institute_of_Information_Technology,_Allahabad_Logo.png
  assets/img/Vector.png
  assets/img/google.jpeg
  assets/img/hint.svg
  assets/img/she1.png
  assets/js/opportunities.js
  opportunity.html
Labels: JWOC, hard
