Repository MightyITExplorer/Website, pull requests merged in 2023-02, with the labels that each got.

#30 Updated the styling of Opportunity ,Study material and tech updates (NEW REQUEST)
  assets/css/theme.css
Labels: enhancement, jWoc, intermediate

#25 my contribution for the issue "Site icon link not working #18"
  index.html
Labels: JWOC, Easy

#22 Added CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: JWOC, Easy

#41 Updated navbar
  assets/css/index.css
  index.html
Labels: JWOC, medium

#60 FIXED :Added google form link to subscribe us button and fixed navbar transition effect while scrolling
  index.html
Labels: JWOC, Easy

#63 Reduced Footer Size
  Website/assets/css/theme.css
  Website/index.html
  Website/news.html
  Website/opportunity.html
  Website/studymaterial.html
  assets/css/theme.css
  index.html
  news.html
  opportunity.html
  studymaterial.html
Labels: JWOC, Easy

#66 Add Scroll To Top Button
  assets/css/index.css
  assets/js/theme.js
  index.html
Labels: JWOC, Easy

#70 Dark mode update
  Website/assets/css/theme.css
  Website/assets/js/theme.js
  index.html
Labels: JWOC, medium

#73 Created contributing.md
  CONTRIBUTING.md
Labels: documentation, JWOC, Easy

#77 Added testimonial
  assets/css/swiper-bundle.min.css
  assets/css/testimonial.css
  assets/img/person/face1.jpeg
  assets/img/person/face2.jpeg
  assets/img/person/face3.jpeg
  assets/img/person/face4.jpeg
  assets/img/person/face5.jpeg
  assets/img/person/face6.jpeg
  assets/img/person/face7.jpeg
  assets/img/person/face8.jpeg
  assets/img/person/face9.jpeg
  assets/js/swiper-bundle.min.js
  assets/js/testimonial.js
  index.html
  testimonial.html
Labels: JWOC, medium

#78 changed hero section
  assets/css/index.css
  assets/css/theme.css
  index.html
Labels: JWOC, Easy

#76 Cards Updated
  assets/css/studymaterial.css
  assets/js/theme.js
  studymaterial.html
Labels: JWOC, medium
